import datetime
from typing import List, Dict, Any

# Curated library of verified free learning resources with YouTube specific analytics metadata
VERIFIED_RESOURCES: List[Dict[str, Any]] = [
    # PYTHON
    {
        "title": "Python for Beginners - Full Video Course",
        "provider": "Programming with Mosh",
        "url": "https://www.youtube.com/watch?v=_uQrJ0TkZlc",
        "resource_type": "Video",
        "skill": "Python",
        "difficulty": "Beginner",
        "duration": "6 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Comprehensive video course covering Python fundamentals, syntax, loops, lists, dictionaries, classes, and modules.",
        "youtube_video_id": "_uQrJ0TkZlc",
        "channel_name": "Programming with Mosh",
        "view_count": 38000000,
        "like_count": 1100000,
        "like_view_ratio": 0.0289,
        "completeness_score": 92,
        "language": "English",
        "published_at": datetime.datetime(2020, 2, 18, 0, 0, 0)
    },
    {
        "title": "Official Python Tutorial Documentation",
        "provider": "Python Software Foundation",
        "url": "https://docs.python.org/3/tutorial/",
        "resource_type": "Documentation",
        "skill": "Python",
        "difficulty": "Beginner",
        "duration": "Self-paced",
        "is_free": True,
        "is_verified": True,
        "hands_on": False,
        "description": "The official tutorial documentation covering the core language details, standard library modules, and advanced features.",
        "completeness_score": 85,
        "language": "English"
    },
    
    # SQL
    {
        "title": "Kudvenkat SQL Server Tutorial Playlist",
        "provider": "kudvenkat",
        "url": "https://www.youtube.com/playlist?list=PL08903FB7ACA1C2FB",
        "resource_type": "Playlist",
        "skill": "SQL",
        "difficulty": "Beginner",
        "duration": "12 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Extremely popular and structured video series covering relational schemas, indexes, keys, joins, subqueries, and stored procedures.",
        "youtube_playlist_id": "PL08903FB7ACA1C2FB",
        "channel_name": "kudvenkat",
        "view_count": 15000000,
        "like_count": 750000,
        "like_view_ratio": 0.05,
        "video_count": 150,
        "completeness_score": 96,
        "language": "English",
        "published_at": datetime.datetime(2018, 5, 20, 0, 0, 0)
    },
    {
        "title": "Intro to SQL Interactive Course",
        "provider": "Kaggle",
        "url": "https://www.kaggle.com/learn/intro-to-sql",
        "resource_type": "Interactive Course",
        "skill": "SQL",
        "difficulty": "Beginner",
        "duration": "3 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Learn to write SQL queries using Google BigQuery with real-world datasets and live interactive workspace coding.",
        "completeness_score": 90,
        "language": "English"
    },
    {
        "title": "Interactive SQL Zoo Practice Tutorials",
        "provider": "SQLZoo",
        "url": "https://sqlzoo.net/",
        "resource_type": "Interactive Course",
        "skill": "SQL",
        "difficulty": "Beginner",
        "duration": "5 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Highly interactive practice platform teaching database querying fundamentals from SELECT to JOINs and CTEs.",
        "completeness_score": 88,
        "language": "English"
    },
    
    # STATISTICS
    {
        "title": "Statistics - A Full University Course",
        "provider": "freeCodeCamp",
        "url": "https://www.youtube.com/watch?v=XXgne3wS3hU",
        "resource_type": "Video",
        "skill": "Statistics",
        "difficulty": "Beginner",
        "duration": "8 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": False,
        "description": "Full statistics college course covering data graphics, measures of central tendency, z-scores, probability, normal distributions, and hypothesis tests.",
        "youtube_video_id": "XXgne3wS3hU",
        "channel_name": "freeCodeCamp.org",
        "view_count": 2500000,
        "like_count": 110000,
        "like_view_ratio": 0.044,
        "completeness_score": 90,
        "language": "English",
        "published_at": datetime.datetime(2020, 10, 27, 0, 0, 0)
    },
    {
        "title": "Intro to Descriptive Statistics",
        "provider": "Udacity",
        "url": "https://www.udacity.com/course/intro-to-statistics--st101",
        "resource_type": "Free Course",
        "skill": "Statistics",
        "difficulty": "Beginner",
        "duration": "8 weeks",
        "is_free": True,
        "is_verified": True,
        "hands_on": False,
        "description": "A comprehensive cloud statistics course covering data visualization, probability distributions, hypothesis testing, and regression basics.",
        "completeness_score": 85,
        "language": "English"
    },
    
    # PANDAS / NUMPY
    {
        "title": "Kaggle Pandas Interactive Course",
        "provider": "Kaggle",
        "url": "https://www.kaggle.com/learn/pandas",
        "resource_type": "Interactive Course",
        "skill": "Pandas",
        "difficulty": "Intermediate",
        "duration": "4 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Interactive notebook tutorial teaching indexing, grouping, merging, and reshaping data using the pandas Python library.",
        "completeness_score": 90,
        "language": "English"
    },
    {
        "title": "NumPy Quickstart Tutorial Guide",
        "provider": "NumPy Community",
        "url": "https://numpy.org/doc/stable/user/quickstart.html",
        "resource_type": "Documentation",
        "skill": "NumPy",
        "difficulty": "Beginner",
        "duration": "Self-paced",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Official introductory guide explaining array construction, vector math operations, slicing, and matrix manipulations.",
        "completeness_score": 80,
        "language": "English"
    },
    
    # MACHINE LEARNING / SCIKIT-LEARN
    {
        "title": "100 Days of Machine Learning Playlist",
        "provider": "CampusX",
        "url": "https://www.youtube.com/playlist?list=PLKnIAqWlhFTV2Q14piE64e0Wj1W7n1bB3",
        "resource_type": "Playlist",
        "skill": "Machine Learning",
        "difficulty": "Intermediate",
        "duration": "30 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Comprehensive structured syllabus from scratch covering math fundamentals, Scikit-Learn algorithms, model tuning, pipelines, and end-to-end deployments.",
        "youtube_playlist_id": "PLKnIAqWlhFTV2Q14piE64e0Wj1W7n1bB3",
        "channel_name": "CampusX",
        "view_count": 13000000,
        "like_count": 650000,
        "like_view_ratio": 0.05,
        "video_count": 134,
        "completeness_score": 98,
        "language": "Hindi-English",
        "published_at": datetime.datetime(2021, 8, 1, 0, 0, 0)
    },
    {
        "title": "Machine Learning Algorithms Video Course",
        "provider": "freeCodeCamp",
        "url": "https://www.youtube.com/watch?v=GwIo3gTOB3I",
        "resource_type": "Video",
        "skill": "Machine Learning",
        "difficulty": "Intermediate",
        "duration": "10 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Deep-dive video lectures explaining regressions, decision trees, neural networks, SVMs, and Scikit-Learn code patterns.",
        "youtube_video_id": "GwIo3gTOB3I",
        "channel_name": "freeCodeCamp.org",
        "view_count": 4500000,
        "like_count": 180000,
        "like_view_ratio": 0.04,
        "completeness_score": 85,
        "language": "English",
        "published_at": datetime.datetime(2021, 3, 2, 0, 0, 0)
    },
    {
        "title": "Intro to Machine Learning Interactive Course",
        "provider": "Kaggle",
        "url": "https://www.kaggle.com/learn/intro-to-machine-learning",
        "resource_type": "Interactive Course",
        "skill": "Machine Learning",
        "difficulty": "Beginner",
        "duration": "3 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Build, evaluate, and tune your first machine learning predictive models using pandas and scikit-learn in Python.",
        "completeness_score": 80,
        "language": "English"
    },
    
    # DOCKER
    {
        "title": "Docker Tutorial for Beginners Course",
        "provider": "TechWorld with Nana",
        "url": "https://www.youtube.com/watch?v=3c-iBgEXNEw",
        "resource_type": "Video",
        "skill": "Docker",
        "difficulty": "Beginner",
        "duration": "3 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Highly structured guide containerizing web projects. Details volumes, networks, registries, Dockerfiles, and compose scripts.",
        "youtube_video_id": "3c-iBgEXNEw",
        "channel_name": "TechWorld with Nana",
        "view_count": 7000000,
        "like_count": 240000,
        "like_view_ratio": 0.034,
        "completeness_score": 88,
        "language": "English",
        "published_at": datetime.datetime(2020, 12, 1, 0, 0, 0)
    },
    {
        "title": "The Hands-on Docker Handbook Guide",
        "provider": "freeCodeCamp",
        "url": "https://www.freecodecamp.org/news/the-docker-handbook/",
        "resource_type": "Tutorial",
        "skill": "Docker",
        "difficulty": "Beginner",
        "duration": "4 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Step-by-step handbook teaching containerization, Dockerfiles, volumes, port mapping, and docker-compose configurations.",
        "completeness_score": 82,
        "language": "English"
    },
    
    # REACT
    {
        "title": "React Tutorial Documentation Guide",
        "provider": "React Community",
        "url": "https://react.dev/learn",
        "resource_type": "Documentation",
        "skill": "React",
        "difficulty": "Beginner",
        "duration": "Self-paced",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Official interactive documentation teaching component structure, hook definitions, props, and states.",
        "completeness_score": 90,
        "language": "English"
    },
    
    # GIT
    {
        "title": "Git & GitHub Crash Course Video",
        "provider": "freeCodeCamp",
        "url": "https://www.youtube.com/watch?v=apGV9Ad7XYY",
        "resource_type": "Video",
        "skill": "Git",
        "difficulty": "Beginner",
        "duration": "1 hour",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Learn to manage files using Git, staging commits, resolving conflicts, branching, and pushing code to GitHub.",
        "youtube_video_id": "apGV9Ad7XYY",
        "channel_name": "freeCodeCamp.org",
        "view_count": 9500000,
        "like_count": 380000,
        "like_view_ratio": 0.04,
        "completeness_score": 80,
        "language": "English",
        "published_at": datetime.datetime(2021, 6, 21, 0, 0, 0)
    },
    
    # FASTAPI
    {
        "title": "FastAPI Complete Video Tutorial",
        "provider": "freeCodeCamp",
        "url": "https://www.youtube.com/watch?v=tLKKmCO4D1g",
        "resource_type": "Video",
        "skill": "FastAPI",
        "difficulty": "Intermediate",
        "duration": "2 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Learn backend REST validation with Pydantic schemas, database relationships (SQLAlchemy), and dynamic routing.",
        "youtube_video_id": "tLKKmCO4D1g",
        "channel_name": "freeCodeCamp.org",
        "view_count": 1800000,
        "like_count": 72000,
        "like_view_ratio": 0.04,
        "completeness_score": 85,
        "language": "English",
        "published_at": datetime.datetime(2021, 10, 15, 0, 0, 0)
    },
    {
        "title": "Official FastAPI Tutorial Guide",
        "provider": "Tiangolo",
        "url": "https://fastapi.tiangolo.com/tutorial/",
        "resource_type": "Documentation",
        "skill": "FastAPI",
        "difficulty": "Beginner",
        "duration": "Self-paced",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Official guide demonstrating REST endpoint declarations, Pydantic type integrations, and automatic Swagger docs.",
        "completeness_score": 85,
        "language": "English"
    },
    {
        "title": "Python for Beginners - Full Video Course (freeCodeCamp)",
        "provider": "freeCodeCamp",
        "url": "https://www.youtube.com/watch?v=rfscVS0vtbw",
        "resource_type": "Video",
        "skill": "Python",
        "difficulty": "Beginner",
        "duration": "4.5 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Full Python programmer course for beginners teaching variables, loops, custom objects, lists, and building basic calculators.",
        "youtube_video_id": "rfscVS0vtbw",
        "channel_name": "freeCodeCamp.org",
        "view_count": 15000000,
        "like_count": 450000,
        "like_view_ratio": 0.03,
        "completeness_score": 88,
        "language": "English",
        "published_at": datetime.datetime(2021, 1, 10, 0, 0, 0)
    },
    {
        "title": "Python Programming Course (GeeksforGeeks)",
        "provider": "GeeksforGeeks",
        "url": "https://www.youtube.com/watch?v=M99Hn_kZ_7k",
        "resource_type": "Video",
        "skill": "Python",
        "difficulty": "Beginner",
        "duration": "2 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "GeeksforGeeks structured video overview detailing core Python keywords, variables, control statements, functions, and OOP definitions.",
        "youtube_video_id": "M99Hn_kZ_7k",
        "channel_name": "GeeksforGeeks",
        "view_count": 600000,
        "like_count": 18000,
        "like_view_ratio": 0.03,
        "completeness_score": 82,
        "language": "English",
        "published_at": datetime.datetime(2022, 6, 12, 0, 0, 0)
    },
    {
        "title": "SQL Tutorial for Beginners (GeeksforGeeks)",
        "provider": "GeeksforGeeks",
        "url": "https://www.youtube.com/watch?v=yW6aXGf2_qM",
        "resource_type": "Video",
        "skill": "SQL",
        "difficulty": "Beginner",
        "duration": "1.5 hours",
        "is_free": True,
        "is_verified": True,
        "hands_on": True,
        "description": "Introductory tutorial focusing on relational database schemas, SELECT queries, WHERE filters, joins, and aggregates.",
        "youtube_video_id": "yW6aXGf2_qM",
        "channel_name": "GeeksforGeeks",
        "view_count": 500000,
        "like_count": 15000,
        "like_view_ratio": 0.03,
        "completeness_score": 80,
        "language": "English",
        "published_at": datetime.datetime(2022, 4, 18, 0, 0, 0)
    }
]
